apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: catalogue
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      tier: db
      project: roboshop
  template:
    metadata:
      labels:
        app: catalogue
        tier: db
        project: roboshop
    spec:
      containers:
      - name: catalogue
        image: srikanthnoone/catalogue:1.0.0
        envFrom:
        - configMapRef:
          name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
      app: catalogue
      tier: db
      project: roboshop
  ports:
  - name: catalogue-port
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue" #protocol://service-name:port/schema


